USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE LOAD_WH WITH WAREHOUSE_SIZE='X-SMALL';
CREATE DATABASE AMG_TEST_DB;
CREATE or replace TABLE AMG_TEST_DB.PUBLIC.FLIGHTS (
        RECORDID NUMBER(38,0),
        OLD_TS_UTC  TIMESTAMP_NTZ(9),
        ALT     NUMBER(38,0),
        DEST    VARCHAR(16777216),
        ORIG    VARCHAR(16777216),
        ID      VARCHAR(16777216),
        ICAO    VARCHAR(16777216),
        LAT     FLOAT,
        LON     FLOAT,
        GEOHASH VARCHAR(16777216)
);

