{
 "title": "Snowflake-AMG-Demo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "airport", "label": "Airport", "query": "KSFO,KSJC,KOAK" },
   {
    "name": "flightID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Arrivals by Airports in Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(id)) as arrivals, dest\nfrom flights_vw\nwhere $__timeFilter(ts_utc)\ngroup by dest"
    }
   ]
  },
  {
   "title": "Number of Arrivals by Airports",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(id)) as arrivals, dest\nfrom flights_vw\nwhere $__timeFilter(ts_utc)\ngroup by dest \norder by arrivals\ndesc"
    }
   ]
  },
  {
   "title": "Altitude for Flight ${flightID} at ${airport}",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT ts_utc as time, alt as altitude\nFROM flights_vw\nWHERE $__timeFilter(ts_utc)\n    AND id= '${flightID}'\n    AND dest = '${airport}'\n    order by time desc"
    }
   ]
  },
  {
   "title": "Altitude chart for $flightID",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ts_utc as time, alt as altitude\nFROM flights_vw\nWHERE $__timeFilter(ts_utc)\n    AND id= '${flightID}'\n    AND dest = '${airport}'\n    order by time"
    }
   ]
  },
  {
   "title": "Flight Tracks of $flightID",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select alt, geohash, id, lat, lon\nfrom flights_vw\nwhere $__timeFilter(ts_utc)\n     AND dest = '${airport}'\n     AND id = '${flightID}'\n    group by geohash,alt,id,lat,lon"
    }
   ]
  },
  {
   "title": "Flight tracks for SFO,SJC,OAK",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "select alt, geohash, id, lat, lon\nfrom flights_vw\nwhere $__timeFilter(ts_utc)\n    and (dest = 'KSFO' or dest = 'KOAK' or dest = 'KSJC')\n    group by geohash,alt,id,lat,lon"
    }
   ]
  }
 ]
}